function computeHeadModel(SubjectName, ConditionName)
% Compute head model for the given subject + condition
% e.g. computeHeadModel('Subject_001','Night1_NegPeak')
    bst_report('Start', []);
    sFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
        'subjectname',   SubjectName, ...
        'condition',     ConditionName, ...
        'tag',           '', ...
        'includebad',    0, ...
        'includeintra',  0, ...
        'includecommon', 0, ...
        'outprocesstab', 'process1');

    if isempty(sFiles)
        disp(['No data found for ' ConditionName ' => skipping head model.']);
        return;
    end

    bst_process('CallProcess', 'process_headmodel', sFiles, [], ...
        'Comment',      '', ...
        'sourcespace',  1, ...   % Cortex surface
        'meg',          3, ...   % Overlapping spheres
        'eeg',          3, ...   % OpenMEEG BEM
        'ecog',         2, ...
        'seeg',         2, ...
        'openmeeg', struct( ...
            'BemFiles',    {{}}, ...
            'BemNames',    {{'Scalp','Skull','Brain'}}, ...
            'BemCond',     [1,0.0125,1], ...
            'BemSelect',   [1,1,1], ...
            'isAdjoint',   0, ...
            'isAdaptative',1, ...
            'isSplit',     0, ...
            'SplitLength', 4000), ...
        'channelfile',  '');
    bst_report('Save', []);
end
