function computeNoiseCov(SubjectName, NoiseCondName)
% Compute Noise Covariance from condition=NoiseCondName in Brainstorm using the entire file duration.
% e.g. computeNoiseCov('Subject_001','Night1_noise')

    bst_report('Start', []);
    sFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
        'subjectname',   SubjectName, ...
        'condition',     NoiseCondName, ...
        'tag',           '', ...
        'includebad',    0, ...
        'includeintra',  0, ...
        'includecommon', 0, ...
        'outprocesstab', 'no');

    if isempty(sFiles)
        disp(['No data files found => condition=' NoiseCondName]);
        return;
    end

    bst_process('CallProcess', 'process_noisecov', sFiles, [], ...
        'baseline',       [], ... % Use entire file duration
        'datatimewindow', [], ... % Use entire file duration
        'sensortypes',    'EEG', ...
        'target',         1, ... % noise covariance
        'dcoffset',       1, ...
        'identity',       0, ...
        'copycond',       0, ...
        'copysubj',       0, ...
        'copymatch',      0, ...
        'replacefile',    1);
    bst_report('Save', []);
end
