% Compute Noise Covariance
% Select file to process --> process compute
function computeNoiseCov(SubjectName, NoiseTime)
bst_report('Start', []);
sFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
    'subjectname',   SubjectName, ...
    'condition',     'noise', ...
    'tag',           '', ...
    'includebad',    0, ...
    'includeintra',  0, ...
    'includecommon', 0, ...
    'outprocesstab', 'no');
bst_process('CallProcess', 'process_noisecov', sFiles, [], ...
    'baseline',       NoiseTime, ...
    'datatimewindow', NoiseTime, ...
    'sensortypes',    'MEG, EEG, SEEG, ECOG', ...
    'target',         1, ...
    'dcoffset',       1, ...
    'identity',       0, ...
    'copycond',       1, ...
    'copysubj',       1, ...
    'copymatch',      0, ...
    'replacefile',    1);
bst_report('Save', []);
end