function generateBEM(SubjectName)
% Generate BEM surface
    bst_report('Start', []);
    bst_process('CallProcess', 'process_generate_bem', [], [], ...
        'subjectname', SubjectName, ...
        'nscalp',      1922, ...
        'nouter',      1922, ...
        'ninner',      1922, ...
        'thickness',   4, ...
        'method',      'brainstorm');
    bst_report('Save', []);
end
