% funciton to select negpeak as BST channel (correct name, incorrect loc)
function negPeakChanFile = getNegPeakChannelFile(SubjectName, ConditionName)
negPeakChanFile = '';
sFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
    'subjectname',   SubjectName, ...
    'condition',     ConditionName, ...
    'tag',           '', ...
    'includebad',    0, ...
    'includeintra',  0, ...
    'includecommon', 0, ...
    'outprocesstab', 'no');

% We pick the last item with a valid .ChannelFile
for i = numel(sFiles):-1:1
    if isfield(sFiles(i), 'ChannelFile') && ~isempty(sFiles(i).ChannelFile)
        negPeakChanFile = sFiles(i).ChannelFile;
        break;
    end
end
end