% Import EEG
% condition = NegPeak; format = EEG-EEGLAB; Epoch time = defualt (+-50ms)
% toolbox/process/fucntion
% Create condition named NegPeak to simplify naming inside pipeline
% validation: show how many EEG data pieces imported

function nImported = importMainEEG(SubjectName, MainEEGFile, EventName, EpochTime)
bst_report('Start', []);
sFiles = bst_process('CallProcess', 'process_import_data_event', [], [], ...
    'subjectname',  SubjectName, ...
    'condition',    'NegPeak', ...
    'datafile',     {{MainEEGFile}, 'EEG-EEGLAB'}, ...
    'eventname',    EventName, ...
    'timewindow',   [], ...
    'epochtime',    EpochTime, ...
    'split',        0, ...
    'createcond',   1, ...
    'ignoreshort',  0, ...
    'channelalign', 0, ...
    'usectfcomp',   0, ...
    'usessp',       0, ...
    'freq',         [], ...
    'baseline',     [], ...
    'blsensortypes','MEG, EEG');
bst_report('Save', sFiles);

nImported = numel(sFiles);
end