% Import noise EEG file for noise cov calculation
% Similar to importMainEEG

function importNoiseEEG(SubjectName, NoiseEEGFile, NoiseTime)
bst_report('Start', []);
bst_process('CallProcess', 'process_import_data_time', [], [], ...
    'subjectname',   SubjectName, ...
    'condition',     'noise', ...
    'datafile',      {{NoiseEEGFile}, 'EEG-EEGLAB'}, ...
    'timewindow',    NoiseTime, ...
    'split',         0, ...
    'ignoreshort',   0, ...
    'channelalign',  0, ...
    'usectfcomp',    0, ...
    'usessp',        0, ...
    'freq',          [], ...
    'baseline',      [], ...
    'blsensortypes', 'MEG, EEG');
bst_report('Save', []);
end