% Import anatomy
% Use process_import_anatomy.m in toolbox/process/fucntion
% Set import anatomy format as FreeSurfer (format of m2m_xxx folder)
% Anatomy validation removed

function importAnatomy(SubjectName, AnatDir)
bst_process('CallProcess', 'process_import_anatomy', [], [], ...
    'subjectname', SubjectName, ...
    'mrifile', {AnatDir, "FreeSurfer"}, ...
    'nvertices', 15000, ...
    'nas', [127,213,139], ...
    'lpa', [52,113,96], ...
    'rpa', [202,113,91]);
end