function importAnatomy(SubjectName, AnatDir)
% Import anatomy
% Use process_import_anatomy
    bst_process('CallProcess', 'process_import_anatomy', [], [], ...
        'subjectname', SubjectName, ...
        'mrifile', {AnatDir, "FreeSurfer"}, ...
        'nvertices', 15000, ...
        'nas', [127,213,139], ...
        'lpa', [52,113,96], ...
        'rpa', [202,113,91]);
end