% Source recosntruction step (sLORETA)
% Select all NegPeak in protocol and compute
% validation: screenshot source map
function runSLORETA(SubjectName)
bst_report('Start', []);
sFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
    'subjectname',   SubjectName, ...
    'condition',     'NegPeak', ...
    'tag',           '', ...
    'includebad',    0, ...
    'includeintra',  0, ...
    'includecommon', 0, ...
    'outprocesstab', 'process1');
bst_process('CallProcess', 'process_inverse_2018', sFiles, [], ...
    'output', 2, ...
    'inverse', struct( ...
        'Comment',         'sLORETA: EEG', ...
        'InverseMethod',   'minnorm', ...
        'InverseMeasure',  'sloreta', ...
        'SourceOrient',    {{'fixed'}}, ...
        'Loose',           0.2, ...
        'UseDepth',        0, ...
        'WeightExp',       0.5, ...
        'WeightLimit',     10, ...
        'NoiseMethod',     'reg', ...
        'NoiseReg',        0.1, ...
        'SnrMethod',       'fixed', ...
        'SnrRms',          1e-06, ...
        'SnrFixed',        3, ...
        'ComputeKernel',   1, ...
        'DataTypes',       {{'EEG'}}));
bst_report('Save', []);
end