function runSLORETA(SubjectName, ConditionName)
% runSLORETA for the specified ConditionName (e.g. "Night1_NegPeak").

    bst_report('Start', []);
    sFiles = bst_process('CallProcess', 'process_select_files_data', [], [], ...
        'subjectname',   SubjectName, ...
        'condition',     ConditionName, ...
        'tag',           '', ...
        'includebad',    0, ...
        'includeintra',  0, ...
        'includecommon', 0, ...
        'outprocesstab', 'process1');

    if isempty(sFiles)
        disp(['No data found for condition=', ConditionName, ' => skipping sLORETA.']);
        return;
    end

    bst_process('CallProcess', 'process_inverse_2018', sFiles, [], ...
        'output', 2, ...  % Kernel only: one per file
        'inverse', struct( ...
            'Comment',         ['sLORETA: EEG for ' ConditionName], ...
            'InverseMethod',   'minnorm', ...
            'InverseMeasure',  'sloreta', ...
            'SourceOrient',    {{'fixed'}}, ...
            'Loose',           0.2, ...
            'UseDepth',        0, ...
            'WeightExp',       0.5, ...
            'WeightLimit',     10, ...
            'NoiseMethod',     'reg', ...
            'NoiseReg',        0.1, ...
            'SnrMethod',       'fixed', ...
            'SnrRms',          1e-06, ...
            'SnrFixed',        3, ...
            'ComputeKernel',   1, ...
            'DataTypes',       {{'EEG'}}));
    bst_report('Save', []);
end
